---
# tasks file for create-user
- name: "Add the user {{ user }} "
  user:
    name: "{{ user }}"
- name: "create user/{{ user }} password "
  shell:
    cmd: |
      chpasswd <<< "{{user}}:{{password}}"
