- name: config machines to leave AD Domain
  hosts: "{{ target }}"
#  user: root
  become: true

  vars:
    AD_Domain: dev.mdi
    username: linux-jdomain-svc
  vars_files:
#    - ../../files/prod-adsvcaccount-pass.yaml
    - ../../files/prod-ad-var.yaml
  tasks:
  - name: leave Domain
    shell:
      cmd: |
        realm leave {{ AD_Domain }} -U {{ username }} -r << EOF 
        {{password}}
        EOF
