---
# tasks file for change-password
- name: check  "{{ user }}" exist
  getent:
    database: passwd
    key: "{{ user }}"
- name: Change "{{user}}" password
  user:
    name: "{{ user }}"
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"
