- name: config xagt on machines
  hosts: "{{ target }}"
  become: true
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /root/ansible-playbooks/files/agent_config.json
      dest: /src/
      owner: root
      group: root
      mode: '0650'
  - name: Copy file with owner and permissions
    copy:
      src: /root/ansible-playbooks/rpms/xagt-32.30.16-1.el7.x86_64.rpm
      dest: /src/
      owner: root
      group: root
      mode: '0650'
  - name: check installed or not
    shell:
      cmd: |
        rpm -qa xagt
    register: result
  - name: install xagt
    shell:
      chdir: /src/
      cmd: |
        rpm -ivh xagt-32.30.16-1.el7.x86_64.rpm
    when: result.stdout == ""
  - name: run agent script
    shell:
      chdir: /src/
      cmd: |
         /opt/fireeye/bin/xagt -i agent_config.json
    when: result.stdout == ""
  - name: start and enable xagt
    tags: start
    systemd:
      daemon_reload: yes
      name: xagt
      state: started
      enabled: yes
    ignore_errors: yes
    register: result
  - name: try start and enable service manual
    shell:
      cmd: |
        systemctl start xagt
        systemctl enable xagt
    when: result.failed 

